#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
#
# tools/gen_entropy_lut.py
#
# Generates the Shannon entropy lookup table for the BEAMFS Radiation
# Event Journal. Output is a C fragment intended to be pasted into
# edac.c between the SENTINEL markers.
#
# Reproducibility:
#   - deterministic (no RNG, no system time, no external data)
#   - runs to completion in O(1) wallclock
#   - identical bit-exact output across Python 3.x versions
#
# Mathematical definition:
#   For a list of N corrected positions distributed across B=8 bins,
#   the Shannon entropy estimator is:
#       H = -sum_{i=0..B-1} (k_i / N) * log2(k_i / N)
#   where k_i is the count of positions in bin i.
#
#   This LUT precomputes f(N, k) = -(k/N) * log2(k/N) in Q16.16 fixed
#   point so that runtime computation reduces to:
#       H_q16 = sum_{i=0..B-1} LUT[N][bin_count[i]]
#   No FPU, no division at runtime (only one division per position
#   for bin index computation).
#
#   Boundary: f(N, 0) = 0 by convention (0 * log 0 = 0).
#   Domain:   N in [1, 8] (= BEAMFS_RS_PARITY/2), k in [0, N].
#
# Usage:
#   ./tools/gen_entropy_lut.py        prints C fragment to stdout
#   ./tools/gen_entropy_lut.py -v     also prints float values to stderr
#
# Author: roastercode - Aurelien DESBRIERES <aurelien@hackers.camp>

import hashlib
import math
import sys

N_MAX = 8           # BEAMFS_RS_PARITY / 2 = max correctable symbols
B = 8               # BEAMFS_RS_ENTROPY_BINS
Q = 16              # BEAMFS_RS_ENTROPY_Q (fractional bits in Q16.16)
SCALE = 1 << Q      # 65536


def f_term_float(N: int, k: int) -> float:
    """f(N, k) = -(k/N) * log2(k/N), with f(N, 0) = 0 by convention."""
    if k == 0:
        return 0.0
    p = k / N
    return -p * math.log2(p)


def f_term_q16_16(N: int, k: int) -> int:
    """Q16.16 fixed-point representation of f(N, k), rounded to nearest."""
    val = f_term_float(N, k)
    # Round half to even for determinism across platforms
    return int(round(val * SCALE))


def emit_c_fragment() -> str:
    """Emit the C array as a string ready to paste into edac.c."""
    lines = []
    lines.append("/*")
    lines.append(" * Shannon entropy term LUT in Q16.16 fixed point.")
    lines.append(" *")
    lines.append(" * Auto-generated by tools/gen_entropy_lut.py -- DO NOT EDIT.")
    lines.append(" *")
    lines.append(" * LUT[N][k] = round(-(k/N) * log2(k/N) * 2^16) for N in [1,8],")
    lines.append(" *           = 0 for k == 0 (or N == 0, unused).")
    lines.append(" *")
    lines.append(" * To regenerate after a parameter change:")
    lines.append(" *   ./tools/gen_entropy_lut.py")
    lines.append(" * The output between the SENTINEL markers below should match")
    lines.append(" * byte-for-byte.")
    lines.append(" */")
    lines.append("/* SENTINEL_LUT_BEGIN -- generator hash %s */" %
                 GENERATOR_SHA256_PLACEHOLDER)
    lines.append("static const __u32 beamfs_rs_entropy_term_q16_16[%d][%d] = {" %
                 (N_MAX + 1, N_MAX + 1))

    for N in range(0, N_MAX + 1):
        if N == 0:
            comment = "    /* [0] unused */"
            row = "    [0] = { 0, },"
            lines.append(row + comment)
            continue

        # Build the row: indices 0..N have meaningful values, N+1..N_MAX are 0
        # (they are unreachable but present so the table is dense).
        values = []
        for k in range(0, N + 1):
            v = f_term_q16_16(N, k)
            values.append(v)
        # Pad with zeros up to N_MAX for a uniform [N_MAX+1][N_MAX+1] shape
        while len(values) < N_MAX + 1:
            values.append(0)

        # Format: 8 values per line, 5-digit padded
        formatted = ", ".join("%5u" % v for v in values)
        lines.append("    [%d] = { %s }," % (N, formatted))

    lines.append("};")
    lines.append("/* SENTINEL_LUT_END */")
    return "\n".join(lines) + "\n"


def main():
    verbose = "-v" in sys.argv

    if verbose:
        sys.stderr.write("# Shannon entropy LUT preview (float values):\n")
        sys.stderr.write("# N\\k  ")
        for k in range(0, N_MAX + 1):
            sys.stderr.write("    %d    " % k)
        sys.stderr.write("\n")
        for N in range(1, N_MAX + 1):
            sys.stderr.write("# N=%d  " % N)
            for k in range(0, N + 1):
                v = f_term_float(N, k)
                # Add 0.0 to coerce -0.0 (float artifact at boundary k=N) to +0.0
                sys.stderr.write("%7.4f  " % (v + 0.0))
            sys.stderr.write("\n")
        sys.stderr.write("\n")

    sys.stdout.write(emit_c_fragment())


# Generator self-hash for traceability: written into the SENTINEL line.
# Computed below by reading this very file at startup. If unavailable
# (script piped from stdin), uses a placeholder.
def _self_sha256():
    try:
        with open(__file__, "rb") as fh:
            return hashlib.sha256(fh.read()).hexdigest()[:16]
    except (NameError, OSError):
        return "unavailable"


GENERATOR_SHA256_PLACEHOLDER = _self_sha256()


if __name__ == "__main__":
    main()
